# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 07a0eba026f9ea585dedb69f57d1d8dd4853e59806267adccb3831d91036d8d978091afae6bd98e141a5fa1446f93d8521c448b66dd669ba681aa9d18742d17d

test:
  secret_key_base: c88bddc9fbd276bcf3aa96c0d18fa92bc1428e001159fbfa313708cfa3d69d6f33fca8ba02ea211060b3132b946c823a84b8bccdc6276d3560382b0ac93fa2e1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
